hp:
  lr: [0.005, 0.01]

  hidden_dim: [64, 128]
  dropout: [0.1, 0.2]

  num_heads: [4, 8]
  num_layers: [2, 3]

  num_trees: [5, 10]
  tree_depth: [3, 4]

  alpha: [0.1, 0.2, 0.3]

num_epochs: 500
patience: 50
